### ISSUE TITLE
Configurar cache para login offline

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/migracaoUnivention#3]
**A sua melhoria está relacionada com um problema ? Por favor descreva.**
Talvez

**Descreva a solução que você gostaria**
Continuar funcionando o cache de senha para login ldap após a migração para o UCS

**Descreva as alternativas que você considerou**
Verificar se após a migração da estação de trabalho para o UCS, o cache ainda continua funcionando. 

**Contexto adicional**

- Testar após fechar issue #2  

- Caso não esteja funcionando (o que é provável) Verificar quais são as configurações necessárias para que passe a funcionar.

**Comment by rodrigoferraro** [comment]
hein @diemello , daí nesses casos onde a issue está com "helpwanted" seria legal colocar um comentario aqui mencionando quem poderia ajudar, e descrevendo qual ajuda precisa..

**Comment by cpinheiro26** [comment]
Desativada a interface de rede para testar o cache do UCS na estação de trabalho. Login localmente com o cache bem sucedido, o UCS cria/usa metodologia própria de cache quando uma estação é integrada ao domínio dele e não utiliza formato de cache anteriormente aplicada a rede CMC no antigo servidor ldap defasado.

**Comment by rodrigoferraro** [comment]
@diemello , @cpinheiro26 , quando a questão, que precisava da ajuda, foi esclarecida, dá pra tirar a TAG.. tudo pra facilitar a comunicação visual.

**Comment by diemello** [comment]
> @diemello , @cpinheiro26 , quando a questão, que precisava da ajuda, foi esclarecida, dá pra tirar a TAG.. tudo pra facilitar a comunicação visual.
> Mas isso durante o processo né.. se com a ajuda se fechou a issue, daí acho q nem precisa né..

A TAG foi incluída pois achei que seria necessário envolver mais pessoas posteriormente, não foi necessário.

Este tipo de comentário na issue perde o sentido, e pode atrapalhar tanto quanto uma "TAG errada" principalmente com ela **fechada** Por que tirar tags de issues finalizadas??.
Estamos aprendendo a usar a ferramenta corretamente. E isso vem com erros ou formas novas de se utilizar.

**Comment by rodrigoferraro** [comment]
Calma.. tô comentando pra gente ir acertando as coisas.. depois deletamos esses comentários. Dá até pra criar uma issue pra lembrar de fazer isso rsrs..
Ceis precisam aprender a conversar.. porque tanto estresse? De boa.. 
Talvez na próxima eu mande um áudio proceis sentirem a vibe pelo tom da voz.
